export let mockData = [
  {
    guid: 34,
    name: "Lanaya",
    race: 11,
    class: 2,
    gender: 1,
    level: 19,
    map: 0,
    instance_id: 0,
    zone: 44,
    guildId: 1,
    guildName: "The Alliance",
  },
  {
    guid: 1992,
    name: "Margareth",
    race: 7,
    class: 8,
    gender: 1,
    level: 1,
    map: 0,
    instance_id: 0,
    zone: 1,
    guildId: null,
    guildName: null,
  },
  {
    guid: 1991,
    name: "Leo",
    race: 5,
    class: 4,
    gender: 2,
    level: 11,
    map: 0,
    instance_id: 0,
    zone: 1,
    guildId: null,
    guildName: null,
  },
  {
    guid: 1990,
    name: "John",
    race: 10,
    class: 1,
    gender: 2,
    level: 11,
    map: 0,
    instance_id: 0,
    zone: 1,
    guildId: null,
    guildName: null,
  },
  {
    guid: 1988,
    name: "Jenny",
    race: 2,
    class: 3,
    gender: 2,
    level: 11,
    map: 0,
    instance_id: 0,
    zone: 1,
    guildId: null,
    guildName: null,
  },
];
